apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvLWRiLXNlcnZpY2U6MjcwMTcvb3JkZXJkYj9hdXRoU291cmNlPWFkbWlu # base64 encoded mongodb://admin:password@mongo-db-service:27017/orderdb?authSource=admin
  rabbitmq-url: YW1xcDovL2FkbWluOnBhc3N3b3JkQHJhYmJpdG1xLXNlcnZpY2U6NTY3Mg== # base64 encoded amqp://admin:password@rabbitmq-service:5672
