apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvLWRiLXNlcnZpY2U6MjcwMTcvcGF5bWVudGRiP2F1dGhTb3VyY2U9YWRtaW4= # base64 encoded mongodb://admin:password@mongo-db-service:27017/paymentdb?authSource=admin
  rabbitmq-url: YW1xcDovL2FkbWluOnBhc3N3b3JkQHJhYmJpdG1xLXNlcnZpY2U6NTY3Mg== # base64 encoded amqp://admin:password@rabbitmq-service:5672
  stripe-secret-key: c2tfdGVzdF8xMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA= # base64 encoded sk_test_123456789012345678901234567890
