apiVersion: v1
kind: Secret
metadata:
  name: shared-secret
type: Opaque
data:
  mongodb-root-password: cGFzc3dvcmQ= # base64 encoded password
  rabbitmq-password: cGFzc3dvcmQ= # base64 encoded password
  redis-password: "" # no password for redis
