apiVersion: v1
kind: Service
metadata:
  name: restohub-frontend
  labels:
    app: restohub-frontend
spec:
  selector:
    app: restohub-frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
