apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvLWRiLXNlcnZpY2U6MjcwMTcvcHJvZHVjdGRiP2F1dGhTb3VyY2U9YWRtaW4= # base64 encoded mongodb://admin:password@mongo-db-service:27017/productdb?authSource=admin
  rabbitmq-url: YW1xcDovL2FkbWluOnBhc3N3b3JkQHJhYmJpdG1xLXNlcnZpY2U6NTY3Mg== # base64 encoded amqp://admin:password@rabbitmq-service:5672
