apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-secret
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvLWRiLXNlcnZpY2U6MjcwMTcvaW52ZW50b3J5ZGI/YXV0aFNvdXJjZT1hZG1pbg== # base64 encoded mongodb://admin:password@mongo-db-service:27017/inventorydb?authSource=admin
  rabbitmq-url: YW1xcDovL2FkbWluOnBhc3N3b3JkQHJhYmJpdG1xLXNlcnZpY2U6NTY3Mg== # base64 encoded amqp://admin:password@rabbitmq-service:5672
